workflows:
  build_debug_apk:
    name: Build Debug APK
    max_build_duration: 60 # Max build time in minutes
    environment:
      vars:
        GRADLEW_PATH: ./gradlew
        ANDROID_BUILD_TYPE: debug
    scripts:
      - name: Build Debug APK
        script: |
          $GRADLEW_PATH assemble$ANDROID_BUILD_TYPE
    artifacts:
      - app/build/outputs/apk/$ANDROID_BUILD_TYPE/app-$ANDROID_BUILD_TYPE.apk
