workflows:
  build_debug_apk:
    name: Build Debug APK
    environment:
      android:
        api_level: 30
        build_tools_version: 30.0.3
    scripts:
      - name: Install Dependencies
        script: |
          ./gradlew dependencies
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - build/outputs/apk/debug/app-debug.apk
